#- hosts: localhost
#
#  roles:
#
#      - { role: ansibe-role-raspbian-configure,
#          essid: CRACK,
#          psk: sagichdirnicht
#        }

- hosts: raspberry
  roles:
     - { role: ansibe-role-raspbian-configure,
         dest_sd: false,
         dest_img: false,
         lan_iface: eth0,
         inet_iface: eth1,
         ap_iface: wlan0,
         sd_mount_rootfs_dir : '',
         get_raspbian: false,
         raspbian_image: 2015-02-16-wheezy-raspbian-wificlient-2015-04-28.img
       }

